### ISSUE TITLE
Can i create a new property in EXIF collection ?

### ISSUE THREAD

**Issue by fehernyul** [spacycoder/flutter_exif#2]
Hi,
Can i create a new property in EXIF collection or just modify the existing properties?

Thank you!
Gabor

**Comment by spacycoder** [comment]
Not sure if i understand your question. But if you are asking if you can create custom tags, then no you can't. If you want to store custom data i recommend you use "TAG_USER_COMMENT". 

example:
`await exif.setAttribute(TAG_USER_COMMENT, '{"my_custom": "json data structure"}');`

**Comment by spacycoder** [comment]
Sorry for the late answer btw :sweat_smile:
